services:
  movie-service:
    image: movie-service
    build: ./movie-service
    environment:
      "actor-service.url": "http://actor-service:8080/api/actors/"
      "review-service.url": "http://review-service:8080/api/reviews"
    ports:
      - "8080:8080"
  actor-service:
    image: actor-service
    build: ./actor-service
  review-service:
    image: review-service
    build: ./review-service